### ISSUE TITLE
Camera: Out of Resources

### ISSUE THREAD

**Issue by Rishan123** [andrewfell/CERC-PIWars2019#2]
`Traceback (most recent call last):
  File "/home/pi/Programs/Github/Pi Wars 2019/Camera/motor_vision.py", line 26, in <module>
    camera = PiCamera()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/lib/python3/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
`

How do I fix this?
@andrewfell

**Comment by andrewfell** [comment]
Rishan, 
Try having a look at this link:
https://raspberrypi.stackexchange.com/questions/63182/picamerammalerror-failed-to-enable-connection-out-of-resources-other-than-mem.

Maybe post your code here?
